/**
 * VStack
 * A flex container that stacks children vertically with consistent spacing
 *
 * @category layout
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/vstack.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const vstackVariants = cva('flex flex-col', {
  variants: {
    gap: {
      none: 'gap-0',
      xs: 'gap-1',
      sm: 'gap-2',
      md: 'gap-4',
      lg: 'gap-6',
      xl: 'gap-8',
    },
    align: {
      start: 'items-start',
      center: 'items-center',
      end: 'items-end',
      stretch: 'items-stretch',
    },
    justify: {
      start: 'justify-start',
      center: 'justify-center',
      end: 'justify-end',
      between: 'justify-between',
      around: 'justify-around',
      evenly: 'justify-evenly',
    },
  },
  defaultVariants: {
    gap: 'md',
    align: 'stretch',
    justify: 'start',
  },
});

export interface VStackProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'ref'>,
    VariantProps<typeof vstackVariants> {
  gap?: 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  align?: 'start' | 'center' | 'end' | 'stretch';
  justify?: 'start' | 'center' | 'end' | 'between' | 'around' | 'evenly';

  className?: string;
  children?: React.ReactNode;
}

export const VStack = React.forwardRef<HTMLDivElement, VStackProps>(
  ({ gap, align, justify, children, className, ...rest }, ref) => {
    return (
      <div ref={ref} className={cn(vstackVariants({ gap, align, justify }), className)} {...rest}>
        {children}
      </div>
    );
  },
);

VStack.displayName = 'VStack';

export default VStack;
