/**
 * Modal
 * A dialog overlay that appears above page content
 *
 * @category overlay
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/modal.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const modalVariants = cva('fixed inset-0 z-50 flex items-center justify-center', {
  variants: {
    size: {
      sm: 'max-w-sm',
      md: 'max-w-md',
      lg: 'max-w-lg',
      xl: 'max-w-xl',
      full: 'max-w-full mx-4',
    },
    animation: {
      none: '',
      fade: 'animate-in fade-in-0',
      scale: 'animate-in fade-in-0 zoom-in-95',
      slide: 'animate-in slide-in-from-bottom-2',
    },
  },
  defaultVariants: {
    size: 'md',
    animation: 'scale',
  },
});

export type ModalSize = 'sm' | 'md' | 'lg' | 'xl' | 'full';

export interface ModalProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'ref'>,
    VariantProps<typeof modalVariants> {
  size?: 'sm' | 'md' | 'lg' | 'xl' | 'full';
  animation?: 'none' | 'fade' | 'scale' | 'slide';
  open?: boolean;
  onClose?: () => void;

  className?: string;
  children?: React.ReactNode;
}

export const Modal = React.forwardRef<HTMLDivElement, ModalProps>(
  ({ size, animation, open, onClose, children, className, ...rest }, ref) => {
    return (
      <>
        {open && (
          <>
            <div
              className="fixed inset-0 z-40 bg-black/50 backdrop-blur-sm"
              onClick={onClose}
              aria-hidden="true"
            />
            <div
              ref={ref}
              role="dialog"
              aria-modal="true"
              className={cn(modalVariants({ size, animation }), className)}
              {...rest}
            >
              {children}
            </div>
          </>
        )}
      </>
    );
  },
);

Modal.displayName = 'Modal';

export const ModalHeader = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('flex flex-col space-y-1.5 p-6 pb-0', className)} {...props} />
  ),
);
ModalHeader.displayName = 'ModalHeader';

export const ModalTitle = React.forwardRef<
  HTMLHeadingElement,
  React.HTMLAttributes<HTMLHeadingElement>
>(({ className, ...props }, ref) => (
  <h2
    ref={ref}
    className={cn('text-lg font-semibold leading-none tracking-tight', className)}
    {...props}
  />
));
ModalTitle.displayName = 'ModalTitle';

export const ModalDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <p ref={ref} className={cn('text-sm text-muted-foreground', className)} {...props} />
));
ModalDescription.displayName = 'ModalDescription';

export const ModalBody = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => <div ref={ref} className={cn('p-6', className)} {...props} />,
);
ModalBody.displayName = 'ModalBody';

export const ModalFooter = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={cn('flex items-center justify-end gap-2 p-6 pt-0', className)}
      {...props}
    />
  ),
);
ModalFooter.displayName = 'ModalFooter';

export const ModalClose = React.forwardRef<
  HTMLButtonElement,
  React.ButtonHTMLAttributes<HTMLButtonElement>
>(({ className, ...props }, ref) => (
  <button
    ref={ref}
    type="button"
    className={cn(
      'absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity',
      'hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
      'disabled:pointer-events-none',
      className,
    )}
    {...props}
  >
    <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
    </svg>
    <span className="sr-only">Close</span>
  </button>
));
ModalClose.displayName = 'ModalClose';

export default Modal;
