/**
 * Tailwind CSS Preset
 *
 * @generated This file was generated by foundry/generators/generate-tokens.ts
 * DO NOT EDIT DIRECTLY
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        // Semantic colors
        primary: {
          DEFAULT: 'var(--colors-semantic-primary)',
          foreground: 'var(--colors-surface-background)',
        },
        secondary: {
          DEFAULT: 'var(--colors-semantic-secondary)',
          foreground: 'var(--colors-surface-background)',
        },
        destructive: {
          DEFAULT: 'var(--colors-semantic-destructive)',
          foreground: 'var(--colors-surface-background)',
        },
        success: {
          DEFAULT: 'var(--colors-semantic-success)',
          foreground: 'var(--colors-surface-background)',
        },
        warning: {
          DEFAULT: 'var(--colors-semantic-warning)',
          foreground: 'var(--colors-surface-background)',
        },
        // Surface colors
        background: 'var(--colors-surface-background)',
        foreground: 'var(--colors-surface-foreground)',
        card: {
          DEFAULT: 'var(--colors-surface-card)',
          foreground: 'var(--colors-surface-cardForeground)',
        },
        popover: {
          DEFAULT: 'var(--colors-surface-popover)',
          foreground: 'var(--colors-surface-popoverForeground)',
        },
        muted: {
          DEFAULT: 'var(--colors-surface-muted)',
          foreground: 'var(--colors-surface-mutedForeground)',
        },
        accent: {
          DEFAULT: 'var(--colors-surface-muted)',
          foreground: 'var(--colors-surface-foreground)',
        },
        // Border
        border: 'var(--colors-border-default)',
        input: 'var(--colors-border-input)',
        ring: 'var(--colors-border-ring)',
      },
      borderRadius: {
        sm: 'var(--radius-scale-sm)',
        md: 'var(--radius-scale-md)',
        lg: 'var(--radius-scale-lg)',
        xl: 'var(--radius-scale-xl)',
      },
      fontFamily: {
        sans: 'var(--typography-fontFamily-sans)',
        mono: 'var(--typography-fontFamily-mono)',
      },
    },
  },
  plugins: [],
};
