/**
 * TypeScript Token Exports
 *
 * @generated This file was generated by foundry/generators/generate-tokens.ts
 * DO NOT EDIT DIRECTLY
 */

export const colorsTokens = {
  'color-primitive-blue': 'var(--color-primitive-blue)',
  'color-primitive-indigo': 'var(--color-primitive-indigo)',
  'color-primitive-purple': 'var(--color-primitive-purple)',
  'color-primitive-pink': 'var(--color-primitive-pink)',
  'color-primitive-green': 'var(--color-primitive-green)',
  'color-primitive-teal': 'var(--color-primitive-teal)',
  'color-primitive-cyan': 'var(--color-primitive-cyan)',
  'color-primitive-orange': 'var(--color-primitive-orange)',
  'color-primitive-red': 'var(--color-primitive-red)',
  'color-primitive-gray': 'var(--color-primitive-gray)',
  'color-primitive-slate': 'var(--color-primitive-slate)',
  'color-primitive-zinc': 'var(--color-primitive-zinc)',
  'color-primitive-neutral': 'var(--color-primitive-neutral)',
  'color-primitive-stone': 'var(--color-primitive-stone)',
  'color-primitive-white': 'var(--color-primitive-white)',
  'color-primitive-black': 'var(--color-primitive-black)',
  'color-primary': 'var(--color-primary)',
  'color-primaryForeground': 'var(--color-primaryForeground)',
  'color-secondary': 'var(--color-secondary)',
  'color-secondaryForeground': 'var(--color-secondaryForeground)',
  'color-destructive': 'var(--color-destructive)',
  'color-destructiveForeground': 'var(--color-destructiveForeground)',
  'color-success': 'var(--color-success)',
  'color-successForeground': 'var(--color-successForeground)',
  'color-warning': 'var(--color-warning)',
  'color-warningForeground': 'var(--color-warningForeground)',
  'color-info': 'var(--color-info)',
  'color-infoForeground': 'var(--color-infoForeground)',
  'color-background': 'var(--color-background)',
  'color-foreground': 'var(--color-foreground)',
  'color-card': 'var(--color-card)',
  'color-cardForeground': 'var(--color-cardForeground)',
  'color-popover': 'var(--color-popover)',
  'color-popoverForeground': 'var(--color-popoverForeground)',
  'color-muted': 'var(--color-muted)',
  'color-mutedForeground': 'var(--color-mutedForeground)',
  'color-accent': 'var(--color-accent)',
  'color-accentForeground': 'var(--color-accentForeground)',
  'color-border': 'var(--color-border)',
  'color-input': 'var(--color-input)',
  'color-ring': 'var(--color-ring)',
} as const;

export type ColorsTokens = typeof colorsTokens;


export const motionTokens = {
  'duration-instant': 'var(--duration-instant)',
  'duration-fast': 'var(--duration-fast)',
  'duration-normal': 'var(--duration-normal)',
  'duration-slow': 'var(--duration-slow)',
  'duration-slower': 'var(--duration-slower)',
  'easing-linear': 'var(--easing-linear)',
  'easing-ease': 'var(--easing-ease)',
  'easing-easeIn': 'var(--easing-easeIn)',
  'easing-easeOut': 'var(--easing-easeOut)',
  'easing-easeInOut': 'var(--easing-easeInOut)',
  'easing-bounce': 'var(--easing-bounce)',
  'semantic-hover-duration': 'var(--semantic-hover-duration)',
  'semantic-hover-easing': 'var(--semantic-hover-easing)',
  'semantic-focus-duration': 'var(--semantic-focus-duration)',
  'semantic-focus-easing': 'var(--semantic-focus-easing)',
  'semantic-enter-duration': 'var(--semantic-enter-duration)',
  'semantic-enter-easing': 'var(--semantic-enter-easing)',
  'semantic-exit-duration': 'var(--semantic-exit-duration)',
  'semantic-exit-easing': 'var(--semantic-exit-easing)',
  'semantic-expand-duration': 'var(--semantic-expand-duration)',
  'semantic-expand-easing': 'var(--semantic-expand-easing)',
} as const;

export type MotionTokens = typeof motionTokens;


export const radiusTokens = {
  'scale-none': 'var(--scale-none)',
  'scale-sm': 'var(--scale-sm)',
  'scale-md': 'var(--scale-md)',
  'scale-lg': 'var(--scale-lg)',
  'scale-xl': 'var(--scale-xl)',
  'scale-2xl': 'var(--scale-2xl)',
  'scale-3xl': 'var(--scale-3xl)',
  'scale-full': 'var(--scale-full)',
  'semantic-button': 'var(--semantic-button)',
  'semantic-input': 'var(--semantic-input)',
  'semantic-card': 'var(--semantic-card)',
  'semantic-badge': 'var(--semantic-badge)',
  'semantic-avatar': 'var(--semantic-avatar)',
  'semantic-dialog': 'var(--semantic-dialog)',
} as const;

export type RadiusTokens = typeof radiusTokens;


export const shadowsTokens = {
  'scale-none': 'var(--scale-none)',
  'scale-sm': 'var(--scale-sm)',
  'scale-md': 'var(--scale-md)',
  'scale-lg': 'var(--scale-lg)',
  'scale-xl': 'var(--scale-xl)',
  'scale-2xl': 'var(--scale-2xl)',
  'scale-inner': 'var(--scale-inner)',
  'semantic-button': 'var(--semantic-button)',
  'semantic-buttonHover': 'var(--semantic-buttonHover)',
  'semantic-card': 'var(--semantic-card)',
  'semantic-cardHover': 'var(--semantic-cardHover)',
  'semantic-dropdown': 'var(--semantic-dropdown)',
  'semantic-dialog': 'var(--semantic-dialog)',
  'semantic-input': 'var(--semantic-input)',
  'semantic-inputFocus': 'var(--semantic-inputFocus)',
} as const;

export type ShadowsTokens = typeof shadowsTokens;


export const spacingTokens = {
  'scale-0': 'var(--scale-0)',
  'scale-1': 'var(--scale-1)',
  'scale-2': 'var(--scale-2)',
  'scale-3': 'var(--scale-3)',
  'scale-4': 'var(--scale-4)',
  'scale-5': 'var(--scale-5)',
  'scale-6': 'var(--scale-6)',
  'scale-7': 'var(--scale-7)',
  'scale-8': 'var(--scale-8)',
  'scale-9': 'var(--scale-9)',
  'scale-10': 'var(--scale-10)',
  'scale-11': 'var(--scale-11)',
  'scale-12': 'var(--scale-12)',
  'scale-14': 'var(--scale-14)',
  'scale-16': 'var(--scale-16)',
  'scale-20': 'var(--scale-20)',
  'scale-24': 'var(--scale-24)',
  'scale-28': 'var(--scale-28)',
  'scale-32': 'var(--scale-32)',
  'scale-px': 'var(--scale-px)',
  'scale-0.5': 'var(--scale-0.5)',
  'scale-1.5': 'var(--scale-1.5)',
  'scale-2.5': 'var(--scale-2.5)',
  'scale-3.5': 'var(--scale-3.5)',
  'semantic-xs': 'var(--semantic-xs)',
  'semantic-sm': 'var(--semantic-sm)',
  'semantic-md': 'var(--semantic-md)',
  'semantic-lg': 'var(--semantic-lg)',
  'semantic-xl': 'var(--semantic-xl)',
  'semantic-2xl': 'var(--semantic-2xl)',
  'component-button-paddingX-sm': 'var(--component-button-paddingX-sm)',
  'component-button-paddingX-md': 'var(--component-button-paddingX-md)',
  'component-button-paddingX-lg': 'var(--component-button-paddingX-lg)',
  'component-button-paddingY-sm': 'var(--component-button-paddingY-sm)',
  'component-button-paddingY-md': 'var(--component-button-paddingY-md)',
  'component-button-paddingY-lg': 'var(--component-button-paddingY-lg)',
  'component-button-gap': 'var(--component-button-gap)',
  'component-input-paddingX': 'var(--component-input-paddingX)',
  'component-input-paddingY': 'var(--component-input-paddingY)',
  'component-card-padding': 'var(--component-card-padding)',
  'component-card-gap': 'var(--component-card-gap)',
} as const;

export type SpacingTokens = typeof spacingTokens;


export const typographyTokens = {
  'fontFamily-sans': 'var(--fontFamily-sans)',
  'fontFamily-mono': 'var(--fontFamily-mono)',
  'fontFamily-display': 'var(--fontFamily-display)',
  'fontSize-xs': 'var(--fontSize-xs)',
  'fontSize-sm': 'var(--fontSize-sm)',
  'fontSize-md': 'var(--fontSize-md)',
  'fontSize-lg': 'var(--fontSize-lg)',
  'fontSize-xl': 'var(--fontSize-xl)',
  'fontSize-2xl': 'var(--fontSize-2xl)',
  'fontSize-3xl': 'var(--fontSize-3xl)',
  'fontSize-4xl': 'var(--fontSize-4xl)',
  'fontSize-5xl': 'var(--fontSize-5xl)',
  'fontWeight-normal': 'var(--fontWeight-normal)',
  'fontWeight-medium': 'var(--fontWeight-medium)',
  'fontWeight-semibold': 'var(--fontWeight-semibold)',
  'fontWeight-bold': 'var(--fontWeight-bold)',
  'lineHeight-tight': 'var(--lineHeight-tight)',
  'lineHeight-normal': 'var(--lineHeight-normal)',
  'lineHeight-relaxed': 'var(--lineHeight-relaxed)',
  'letterSpacing-tight': 'var(--letterSpacing-tight)',
  'letterSpacing-normal': 'var(--letterSpacing-normal)',
  'letterSpacing-wide': 'var(--letterSpacing-wide)',
} as const;

export type TypographyTokens = typeof typographyTokens;

