/**
 * TypeScript Token Exports
 *
 * @generated This file was generated by foundry/generators/generate-tokens.ts
 * DO NOT EDIT DIRECTLY
 */

export const colorsTokens = {
  'description': 'var(--description)',
  'primitives-blue': 'var(--primitives-blue)',
  'primitives-indigo': 'var(--primitives-indigo)',
  'primitives-purple': 'var(--primitives-purple)',
  'primitives-pink': 'var(--primitives-pink)',
  'primitives-green': 'var(--primitives-green)',
  'primitives-teal': 'var(--primitives-teal)',
  'primitives-cyan': 'var(--primitives-cyan)',
  'primitives-orange': 'var(--primitives-orange)',
  'primitives-red': 'var(--primitives-red)',
  'primitives-gray': 'var(--primitives-gray)',
  'primitives-slate': 'var(--primitives-slate)',
  'primitives-zinc': 'var(--primitives-zinc)',
  'primitives-neutral': 'var(--primitives-neutral)',
  'primitives-stone': 'var(--primitives-stone)',
  'primitives-white': 'var(--primitives-white)',
  'primitives-black': 'var(--primitives-black)',
  'semantic-primary': 'var(--semantic-primary)',
  'semantic-secondary': 'var(--semantic-secondary)',
  'semantic-destructive': 'var(--semantic-destructive)',
  'semantic-success': 'var(--semantic-success)',
  'semantic-warning': 'var(--semantic-warning)',
  'semantic-info': 'var(--semantic-info)',
  'surface-background': 'var(--surface-background)',
  'surface-foreground': 'var(--surface-foreground)',
  'surface-card': 'var(--surface-card)',
  'surface-cardForeground': 'var(--surface-cardForeground)',
  'surface-popover': 'var(--surface-popover)',
  'surface-popoverForeground': 'var(--surface-popoverForeground)',
  'surface-muted': 'var(--surface-muted)',
  'surface-mutedForeground': 'var(--surface-mutedForeground)',
  'border-default': 'var(--border-default)',
  'border-input': 'var(--border-input)',
  'border-ring': 'var(--border-ring)',
} as const;

export type ColorsTokens = typeof colorsTokens;


export const motionTokens = {
  'description': 'var(--description)',
  'duration-instant': 'var(--duration-instant)',
  'duration-fast': 'var(--duration-fast)',
  'duration-normal': 'var(--duration-normal)',
  'duration-slow': 'var(--duration-slow)',
  'duration-slower': 'var(--duration-slower)',
  'easing-linear': 'var(--easing-linear)',
  'easing-ease': 'var(--easing-ease)',
  'easing-easeIn': 'var(--easing-easeIn)',
  'easing-easeOut': 'var(--easing-easeOut)',
  'easing-easeInOut': 'var(--easing-easeInOut)',
  'easing-bounce': 'var(--easing-bounce)',
  'semantic-hover-duration': 'var(--semantic-hover-duration)',
  'semantic-hover-easing': 'var(--semantic-hover-easing)',
  'semantic-focus-duration': 'var(--semantic-focus-duration)',
  'semantic-focus-easing': 'var(--semantic-focus-easing)',
  'semantic-enter-duration': 'var(--semantic-enter-duration)',
  'semantic-enter-easing': 'var(--semantic-enter-easing)',
  'semantic-exit-duration': 'var(--semantic-exit-duration)',
  'semantic-exit-easing': 'var(--semantic-exit-easing)',
  'semantic-expand-duration': 'var(--semantic-expand-duration)',
  'semantic-expand-easing': 'var(--semantic-expand-easing)',
} as const;

export type MotionTokens = typeof motionTokens;


export const radiusTokens = {
  'description': 'var(--description)',
  'scale-none': 'var(--scale-none)',
  'scale-sm': 'var(--scale-sm)',
  'scale-md': 'var(--scale-md)',
  'scale-lg': 'var(--scale-lg)',
  'scale-xl': 'var(--scale-xl)',
  'scale-2xl': 'var(--scale-2xl)',
  'scale-3xl': 'var(--scale-3xl)',
  'scale-full': 'var(--scale-full)',
  'semantic-button': 'var(--semantic-button)',
  'semantic-input': 'var(--semantic-input)',
  'semantic-card': 'var(--semantic-card)',
  'semantic-badge': 'var(--semantic-badge)',
  'semantic-avatar': 'var(--semantic-avatar)',
  'semantic-dialog': 'var(--semantic-dialog)',
} as const;

export type RadiusTokens = typeof radiusTokens;


export const shadowsTokens = {
  'description': 'var(--description)',
  'scale-none': 'var(--scale-none)',
  'scale-sm': 'var(--scale-sm)',
  'scale-md': 'var(--scale-md)',
  'scale-lg': 'var(--scale-lg)',
  'scale-xl': 'var(--scale-xl)',
  'scale-2xl': 'var(--scale-2xl)',
  'scale-inner': 'var(--scale-inner)',
  'semantic-button': 'var(--semantic-button)',
  'semantic-buttonHover': 'var(--semantic-buttonHover)',
  'semantic-card': 'var(--semantic-card)',
  'semantic-cardHover': 'var(--semantic-cardHover)',
  'semantic-dropdown': 'var(--semantic-dropdown)',
  'semantic-dialog': 'var(--semantic-dialog)',
  'semantic-input': 'var(--semantic-input)',
  'semantic-inputFocus': 'var(--semantic-inputFocus)',
} as const;

export type ShadowsTokens = typeof shadowsTokens;


export const spacingTokens = {
  'description': 'var(--description)',
  'scale-0': 'var(--scale-0)',
  'scale-1': 'var(--scale-1)',
  'scale-2': 'var(--scale-2)',
  'scale-3': 'var(--scale-3)',
  'scale-4': 'var(--scale-4)',
  'scale-5': 'var(--scale-5)',
  'scale-6': 'var(--scale-6)',
  'scale-7': 'var(--scale-7)',
  'scale-8': 'var(--scale-8)',
  'scale-9': 'var(--scale-9)',
  'scale-10': 'var(--scale-10)',
  'scale-11': 'var(--scale-11)',
  'scale-12': 'var(--scale-12)',
  'scale-14': 'var(--scale-14)',
  'scale-16': 'var(--scale-16)',
  'scale-20': 'var(--scale-20)',
  'scale-24': 'var(--scale-24)',
  'scale-28': 'var(--scale-28)',
  'scale-32': 'var(--scale-32)',
  'scale-px': 'var(--scale-px)',
  'scale-0.5': 'var(--scale-0.5)',
  'scale-1.5': 'var(--scale-1.5)',
  'scale-2.5': 'var(--scale-2.5)',
  'scale-3.5': 'var(--scale-3.5)',
  'semantic-xs': 'var(--semantic-xs)',
  'semantic-sm': 'var(--semantic-sm)',
  'semantic-md': 'var(--semantic-md)',
  'semantic-lg': 'var(--semantic-lg)',
  'semantic-xl': 'var(--semantic-xl)',
  'semantic-2xl': 'var(--semantic-2xl)',
  'component-button-paddingX-sm': 'var(--component-button-paddingX-sm)',
  'component-button-paddingX-md': 'var(--component-button-paddingX-md)',
  'component-button-paddingX-lg': 'var(--component-button-paddingX-lg)',
  'component-button-paddingY-sm': 'var(--component-button-paddingY-sm)',
  'component-button-paddingY-md': 'var(--component-button-paddingY-md)',
  'component-button-paddingY-lg': 'var(--component-button-paddingY-lg)',
  'component-button-gap': 'var(--component-button-gap)',
  'component-input-paddingX': 'var(--component-input-paddingX)',
  'component-input-paddingY': 'var(--component-input-paddingY)',
  'component-card-padding': 'var(--component-card-padding)',
  'component-card-gap': 'var(--component-card-gap)',
} as const;

export type SpacingTokens = typeof spacingTokens;


export const typographyTokens = {
  'description': 'var(--description)',
  'fontFamily-sans': 'var(--fontFamily-sans)',
  'fontFamily-mono': 'var(--fontFamily-mono)',
  'fontFamily-display': 'var(--fontFamily-display)',
  'fontSize-xs': 'var(--fontSize-xs)',
  'fontSize-sm': 'var(--fontSize-sm)',
  'fontSize-md': 'var(--fontSize-md)',
  'fontSize-lg': 'var(--fontSize-lg)',
  'fontSize-xl': 'var(--fontSize-xl)',
  'fontSize-2xl': 'var(--fontSize-2xl)',
  'fontSize-3xl': 'var(--fontSize-3xl)',
  'fontSize-4xl': 'var(--fontSize-4xl)',
  'fontSize-5xl': 'var(--fontSize-5xl)',
  'fontWeight-normal': 'var(--fontWeight-normal)',
  'fontWeight-medium': 'var(--fontWeight-medium)',
  'fontWeight-semibold': 'var(--fontWeight-semibold)',
  'fontWeight-bold': 'var(--fontWeight-bold)',
  'lineHeight-tight': 'var(--lineHeight-tight)',
  'lineHeight-normal': 'var(--lineHeight-normal)',
  'lineHeight-relaxed': 'var(--lineHeight-relaxed)',
  'letterSpacing-tight': 'var(--letterSpacing-tight)',
  'letterSpacing-normal': 'var(--letterSpacing-normal)',
  'letterSpacing-wide': 'var(--letterSpacing-wide)',
} as const;

export type TypographyTokens = typeof typographyTokens;

