/**
 * Breadcrumb
 * Navigation breadcrumb trail
 *
 * @category navigation
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/breadcrumb.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const breadcrumbVariants = cva(
  'flex flex-wrap items-center gap-1.5 break-words text-sm text-muted-foreground',
  {
    variants: {
      size: {
        sm: 'text-xs',
        md: 'text-sm',
        lg: 'text-base',
      },
    },
    defaultVariants: {
      size: 'md',
    },
  },
);

export type BreadcrumbSize = 'sm' | 'md' | 'lg';

export interface BreadcrumbProps
  extends Omit<React.HTMLAttributes<HTMLElement>, 'ref'>,
    VariantProps<typeof breadcrumbVariants> {
  size?: 'sm' | 'md' | 'lg';

  list?: React.ReactNode;
  item?: React.ReactNode;
  separator?: React.ReactNode;
  className?: string;
  children?: React.ReactNode;
}

export const Breadcrumb = React.forwardRef<HTMLElement, BreadcrumbProps>(
  ({ size, list, item, separator, className, children, ...rest }, ref) => {
    return (
      <nav ref={ref} aria-label="breadcrumb" {...rest}>
        <ol className={cn(breadcrumbVariants({ size }), className)}>{children}</ol>
      </nav>
    );
  },
);

Breadcrumb.displayName = 'Breadcrumb';

export const BreadcrumbItem = React.forwardRef<HTMLLIElement, React.HTMLAttributes<HTMLLIElement>>(
  ({ className, ...props }, ref) => (
    <li ref={ref} className={cn('inline-flex items-center gap-1.5', className)} {...props} />
  ),
);
BreadcrumbItem.displayName = 'BreadcrumbItem';

export const BreadcrumbLink = React.forwardRef<
  HTMLAnchorElement,
  React.AnchorHTMLAttributes<HTMLAnchorElement> & { asChild?: boolean }
>(({ className, ...props }, ref) => (
  <a ref={ref} className={cn('transition-colors hover:text-foreground', className)} {...props} />
));
BreadcrumbLink.displayName = 'BreadcrumbLink';

export const BreadcrumbSeparator = ({
  children,
  className,
  ...props
}: React.HTMLAttributes<HTMLSpanElement>) => (
  <span
    role="presentation"
    aria-hidden="true"
    className={cn('[&>svg]:size-3.5', className)}
    {...props}
  >
    {children || (
      <svg fill="none" stroke="currentColor" viewBox="0 0 24 24" className="h-4 w-4">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
      </svg>
    )}
  </span>
);
BreadcrumbSeparator.displayName = 'BreadcrumbSeparator';

export const BreadcrumbPage = React.forwardRef<
  HTMLSpanElement,
  React.HTMLAttributes<HTMLSpanElement>
>(({ className, ...props }, ref) => (
  <span
    ref={ref}
    role="link"
    aria-disabled="true"
    aria-current="page"
    className={cn('font-normal text-foreground', className)}
    {...props}
  />
));
BreadcrumbPage.displayName = 'BreadcrumbPage';

export default Breadcrumb;
