/**
 * TabItem
 * Individual tab button/trigger
 *
 * @category navigation
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/tabitem.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const tabitemVariants = cva(
  'inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
  {
    variants: {
      variant: {
        default:
          'data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm',
        underline:
          'border-b-2 border-transparent rounded-none data-[state=active]:border-primary data-[state=active]:text-foreground',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  },
);

export interface TabItemProps
  extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'ref'>,
    VariantProps<typeof tabitemVariants> {
  variant?: 'default' | 'underline';
  active?: boolean;

  className?: string;
  children?: React.ReactNode;
}

export const TabItem = React.forwardRef<HTMLButtonElement, TabItemProps>(
  ({ variant, active, className, children, ...rest }, ref) => {
    return (
      <button
        ref={ref}
        role="tab"
        aria-selected={active}
        data-state={active ? 'active' : 'inactive'}
        className={cn(tabitemVariants({ variant }), className)}
        {...rest}
      >
        {children}
      </button>
    );
  },
);

TabItem.displayName = 'TabItem';

export default TabItem;
