/**
 * Checkbox
 * Binary selection toggle
 *
 * @category input
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/checkbox.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const checkboxVariants = cva(
  'peer shrink-0 border border-input bg-background text-primary focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 rounded',
  {
    variants: {
      size: {
        sm: 'h-3.5 w-3.5',
        md: 'h-4 w-4',
        lg: 'h-5 w-5',
      },
    },
    defaultVariants: {
      size: 'md',
    },
  },
);

export type CheckboxSize = 'sm' | 'md' | 'lg';

export interface CheckboxProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'ref' | 'size'>,
    VariantProps<typeof checkboxVariants> {
  size?: 'sm' | 'md' | 'lg';

  className?: string;
  children?: React.ReactNode;
}

export const Checkbox = React.forwardRef<HTMLInputElement, CheckboxProps>(
  ({ size, className, children, ...rest }, ref) => {
    return (
      <input
        ref={ref}
        type="checkbox"
        className={cn(checkboxVariants({ size }), className)}
        {...rest}
      />
    );
  },
);

Checkbox.displayName = 'Checkbox';

export default Checkbox;
