/**
 * Spacer
 * A flexible spacer that expands to fill available space in flex containers
 *
 * @category layout
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/spacer.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const spacerVariants = cva('flex-grow', {
  variants: {},
  defaultVariants: {},
});

export interface SpacerProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'ref'>,
    VariantProps<typeof spacerVariants> {
  className?: string;
  children?: React.ReactNode;
}

export const Spacer = React.forwardRef<HTMLDivElement, SpacerProps>(
  ({ className, children, ...rest }, ref) => {
    return (
      <div ref={ref} aria-hidden="true" className={cn(spacerVariants({}), className)} {...rest} />
    );
  },
);

Spacer.displayName = 'Spacer';

export default Spacer;
