/**
 * Grid
 * A CSS grid container for creating responsive layouts
 *
 * @category layout
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/grid.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const gridVariants = cva('grid', {
  variants: {
    gap: {
      none: 'gap-0',
      xs: 'gap-1',
      sm: 'gap-2',
      md: 'gap-4',
      lg: 'gap-6',
      xl: 'gap-8',
    },
    cols: {
      '1': 'grid-cols-1',
      '2': 'grid-cols-2',
      '3': 'grid-cols-3',
      '4': 'grid-cols-4',
      '5': 'grid-cols-5',
      '6': 'grid-cols-6',
      '12': 'grid-cols-12',
    },
  },
  defaultVariants: {
    cols: '3',
    gap: 'md',
  },
});

export interface GridProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'ref'>,
    VariantProps<typeof gridVariants> {
  cols?: '1' | '2' | '3' | '4' | '5' | '6' | '12';
  gap?: 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl';

  className?: string;
  children?: React.ReactNode;
}

export const Grid = React.forwardRef<HTMLDivElement, GridProps>(
  ({ cols, gap, children, className, ...rest }, ref) => {
    return (
      <div ref={ref} className={cn(gridVariants({ cols, gap }), className)} {...rest}>
        {children}
      </div>
    );
  },
);

Grid.displayName = 'Grid';

export default Grid;
