/**
 * Textarea
 * Multi-line text input for longer content
 *
 * @category input
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/textarea.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const textareaVariants = cva(
  'w-full rounded-md border border-input bg-background text-foreground transition-colors placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive',
  {
    variants: {
    size: {
      'sm': 'h-8 px-3 text-sm',
      'md': 'h-10 px-4 text-sm',
      'lg': 'h-12 px-5 text-base'
    }
    },
    defaultVariants: {
      size: 'md'
    },
  }
);

export type TextareaSize = 'sm' | 'md' | 'lg';

export interface TextareaProps
  extends Omit<React.TextareaHTMLAttributes<HTMLTextAreaElement>, 'ref'>,
    VariantProps<typeof textareaVariants> {
  size?: 'sm' | 'md' | 'lg';
  rows?: number;
  resize?: 'none' | 'vertical' | 'horizontal' | 'both';

  className?: string;
  children?: React.ReactNode;
}

export const Textarea = React.forwardRef<HTMLTextAreaElement, TextareaProps>(
  ({ size, rows, resize, className, children, ...rest }, ref) => {
    return (
      <textarea
        ref={ref}
        className={cn(textareaVariants({ size }), className)}
        {...rest}
      >
        {children}
      </textarea>
    );
  }
);

Textarea.displayName = 'Textarea';



export default Textarea;