/**
 * Link
 * Navigation link component
 *
 * @category navigation
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/link.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const linkVariants = cva(
  'inline-flex items-center underline-offset-4 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
  {
    variants: {
      variant: {
        default: 'text-primary hover:underline',
        muted: 'text-muted-foreground hover:text-foreground',
        nav: 'text-foreground/60 hover:text-foreground',
        destructive: 'text-destructive hover:underline',
      },
      size: {
        sm: 'text-sm',
        md: 'text-base',
        lg: 'text-lg',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'md',
    },
  },
);

export type LinkSize = 'sm' | 'md' | 'lg';

export interface LinkProps
  extends Omit<React.AnchorHTMLAttributes<HTMLAnchorElement>, 'ref'>,
    VariantProps<typeof linkVariants> {
  variant?: 'default' | 'muted' | 'nav' | 'destructive';
  size?: 'sm' | 'md' | 'lg';
  external?: boolean;

  className?: string;
  children?: React.ReactNode;
}

export const Link = React.forwardRef<HTMLAnchorElement, LinkProps>(
  ({ variant, size, external, className, children, ...rest }, ref) => {
    return (
      <a
        ref={ref}
        className={cn(linkVariants({ variant, size }), className)}
        {...(external ? { target: '_blank', rel: 'noopener noreferrer' } : {})}
        {...rest}
      >
        {children}
        {external && (
          <svg className="ml-1 h-3 w-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
            />
          </svg>
        )}
      </a>
    );
  },
);

Link.displayName = 'Link';

export default Link;
