/**
 * Progress
 * Progress bar to show completion status
 *
 * @category feedback
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/progress.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const progressVariants = cva('relative w-full overflow-hidden rounded-full bg-secondary', {
  variants: {
    size: {
      sm: 'h-1',
      md: 'h-2',
      lg: 'h-4',
    },
  },
  defaultVariants: {
    size: 'md',
  },
});

export type ProgressSize = 'sm' | 'md' | 'lg';

export interface ProgressProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'ref'>,
    VariantProps<typeof progressVariants> {
  size?: 'sm' | 'md' | 'lg';
  value?: number;
  max?: number;
  indicator?: React.ReactNode;
  className?: string;
  children?: React.ReactNode;
}

export const Progress = React.forwardRef<HTMLDivElement, ProgressProps>(
  ({ size, value, max, indicator, className, children, ...rest }, ref) => {
    return (
      <div
        ref={ref}
        role="progressbar"
        aria-valuenow={value}
        aria-valuemin={0}
        aria-valuemax={max}
        className={cn(progressVariants({ size }), className)}
        {...rest}
      >
        <div
          className="h-full w-full flex-1 bg-primary transition-all"
          style={{ transform: `translateX(-${100 - ((value ?? 0) / (max ?? 100)) * 100}%)` }}
        />
      </div>
    );
  },
);

Progress.displayName = 'Progress';

export default Progress;
