/**
 * Backdrop
 * A semi-transparent overlay that covers the page behind modals and drawers
 *
 * @category overlay
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/backdrop.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const backdropVariants = cva('fixed inset-0 z-40 bg-black/50 backdrop-blur-sm', {
  variants: {},
  defaultVariants: {},
});

export interface BackdropProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'ref'>,
    VariantProps<typeof backdropVariants> {
  onClick?: () => void;

  className?: string;
  children?: React.ReactNode;
}

export const Backdrop = React.forwardRef<HTMLDivElement, BackdropProps>(
  ({ onClick, className, children, ...rest }, ref) => {
    return (
      <div ref={ref} className={cn(backdropVariants({}), className)} {...rest}>
        {children}
      </div>
    );
  },
);

Backdrop.displayName = 'Backdrop';

export default Backdrop;
