#!/usr/bin/env tsx
/**
 * Component Generator
 *
 * Generates React components from JSON schemas using category-based handlers.
 * Supports multiple component types: action (buttons), input (forms), surface (cards).
 *
 * Usage: npm run foundry:components
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import type { ComponentSchema, ComponentCategory, GenerationContext } from './core/types';
import { extractSlots } from './core/types';
import { getHandler } from './handlers';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const FOUNDRY_DIR = path.join(__dirname, '..');
const SCHEMAS_DIR = path.join(FOUNDRY_DIR, 'schemas');
const OUTPUT_DIR = path.join(FOUNDRY_DIR, '..', 'src', 'components-generated');

/**
 * Load and parse a schema file
 */
function loadSchema(schemaPath: string): ComponentSchema | null {
  try {
    const content = fs.readFileSync(schemaPath, 'utf-8');
    return JSON.parse(content);
  } catch (error) {
    console.error(`Failed to load schema: ${schemaPath}`, error);
    return null;
  }
}

/**
 * Generate component file using the appropriate handler
 */
function generateComponent(schema: ComponentSchema): string {
  const category = (schema.category || 'action') as ComponentCategory;
  const handler = getHandler(category);

  const elementConfig = handler.getElementConfig(schema);
  const slots = extractSlots(schema);

  const context: GenerationContext = {
    schema,
    category,
    elementConfig,
    slots,
    outputDir: OUTPUT_DIR,
  };

  // Generate parts using handler
  const baseClasses = handler.generateBaseClasses(schema);
  const variantClasses = handler.generateVariantClasses(schema);
  const componentBody = handler.generateComponentBody(context);
  const defaultVariants = Object.entries(schema.variants)
    .map(([key, config]) => `      ${key}: '${config.default}'`)
    .join(',\n');

  // Generate props interface
  const propsInterface = generatePropsInterface(context);

  // Generate props destructure
  const propsDestructure = generatePropsDestructure(context);

  // Additional exports (compound components, etc.)
  const additionalExports = handler.generateAdditionalExports?.(context) || '';

  // Format variant classes for CVA
  const variantClassesStr = Object.entries(variantClasses)
    .map(([key, values]) => {
      const mappings = Object.entries(values)
        .map(([k, v]) => `      '${k}': '${v}'`)
        .join(',\n');
      return `    ${key}: {\n${mappings}\n    }`;
    })
    .join(',\n');

  return `
/**
 * ${schema.name}
 * ${schema.description}
 *
 * @category ${category}
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/${schema.name.toLowerCase()}.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const ${schema.name.toLowerCase()}Variants = cva(
  '${baseClasses}',
  {
    variants: {
${variantClassesStr}
    },
    defaultVariants: {
${defaultVariants}
    },
  }
);

${propsInterface}

export const ${schema.name} = React.forwardRef<${elementConfig.refType}, ${schema.name}Props>(
  ({ ${propsDestructure}, ...rest }, ref) => {
    return (
      ${componentBody}
    );
  }
);

${schema.name}.displayName = '${schema.name}';

${additionalExports}

export default ${schema.name};
`.trim();
}

/**
 * Get list of conflicting HTML attributes that need to be omitted
 */
function getOmittedAttributes(
  schema: ComponentSchema,
  elementConfig: ReturnType<typeof getHandler>['getElementConfig'] extends (
    s: ComponentSchema,
  ) => infer R
    ? R
    : never,
): string[] {
  const omitted = ['ref'];

  // 'size' variant conflicts with HTML size attribute on input/select
  if (schema.variants.size && ['input', 'select', 'textarea'].includes(elementConfig.tag)) {
    omitted.push('size');
  }

  // 'content' slot/prop conflicts with HTMLAttributes.content
  if (schema.slots?.content || schema.props?.content) {
    omitted.push('content');
  }

  return omitted;
}

/**
 * Generate props interface
 */
function generatePropsInterface(context: GenerationContext): string {
  const { schema, elementConfig, slots } = context;
  const { name, variants, props } = schema;

  // Track defined props to avoid duplicates
  const definedProps = new Set<string>();

  // Variant prop types
  const variantTypes = Object.entries(variants)
    .map(([key, config]) => {
      definedProps.add(key);
      const values = config.values.map((v) => `'${v}'`).join(' | ');
      return `  ${key}?: ${values};`;
    })
    .join('\n');

  // Custom prop types from schema (skip if already defined)
  const customProps = props
    ? Object.entries(props)
        .filter(([key]) => !definedProps.has(key))
        .map(([key, config]) => {
          definedProps.add(key);
          const optional = config.required ? '' : '?';
          // Handle ReactNode type - avoid double prefixing React.React.ReactNode
          let type = config.type;
          if (type === 'ReactNode') {
            type = 'React.ReactNode';
          } else if (!type.includes('React.') && type.includes('ReactNode')) {
            type = type.replace(/\bReactNode\b/g, 'React.ReactNode');
          }
          return `  ${key}${optional}: ${type};`;
        })
        .join('\n')
    : '';

  // Slot prop types (skip if already defined in variants or props, and skip 'children' since it's added below)
  const slotProps = slots
    .filter(
      (s) =>
        s.name !== 'root' &&
        s.name !== 'input' &&
        s.name !== 'children' &&
        !definedProps.has(s.name),
    )
    .map((slot) => `  ${slot.name}?: React.ReactNode;`)
    .join('\n');

  // Type aliases for backward compatibility
  const variantTypeAlias = variants.intent
    ? `export type ${name}Variant = ${variants.intent.values.map((v) => `'${v}'`).join(' | ')};`
    : '';
  const sizeTypeAlias = variants.size
    ? `export type ${name}Size = ${variants.size.values.map((v) => `'${v}'`).join(' | ')};`
    : '';

  // Build omit list for conflicting HTML attributes
  const omitted = getOmittedAttributes(schema, elementConfig);
  const omitString = omitted.map((o) => `'${o}'`).join(' | ');

  return `
${variantTypeAlias}
${sizeTypeAlias}

export interface ${name}Props
  extends Omit<React.${elementConfig.attributesType}, ${omitString}>,
    VariantProps<typeof ${name.toLowerCase()}Variants> {
${variantTypes}
${customProps}
${slotProps}
  className?: string;
  children?: React.ReactNode;
}`.trim();
}

/**
 * Generate props destructure list (avoiding duplicates)
 */
function generatePropsDestructure(context: GenerationContext): string {
  const { schema, slots } = context;
  const { variants, props } = schema;

  // Use a Set to avoid duplicates
  const parts = new Set<string>();

  // Add variant keys
  Object.keys(variants).forEach((k) => parts.add(k));

  // Add custom props (may overlap with variants)
  if (props) {
    Object.keys(props).forEach((k) => parts.add(k));
  }

  // Add slot props (may overlap with props)
  slots.filter((s) => s.name !== 'root' && s.name !== 'input').forEach((s) => parts.add(s.name));

  // Always include className and children
  parts.add('className');
  parts.add('children');

  return Array.from(parts).join(', ');
}

/**
 * Generate *Field wrapper component for input category
 */
function generateFieldComponent(schema: ComponentSchema): string | null {
  const category = (schema.category || 'action') as ComponentCategory;

  // Only generate Field wrappers for input category
  if (category !== 'input') return null;

  // Check if formField is explicitly disabled
  if (schema.formField?.enabled === false) return null;

  const handler = getHandler(category);
  const elementConfig = handler.getElementConfig(schema);
  const slots = extractSlots(schema);

  const context: GenerationContext = {
    schema,
    category,
    elementConfig,
    slots,
    outputDir: OUTPUT_DIR,
  };

  // Use handler's field wrapper generator
  if (handler.generateFieldWrapper) {
    return `
/**
 * ${schema.name}Field
 *
 * FormField-wrapped version of ${schema.name} with label, description, and error support.
 *
 * @category ${category}
 * @generated DO NOT EDIT - modify foundry/schemas/${schema.name.toLowerCase()}.schema.json
 */

import * as React from 'react';
import { ${schema.name}, type ${schema.name}Props } from './${schema.name}';

${handler.generateFieldWrapper(context)}
`.trim();
  }

  return null;
}

/**
 * Generate index file with all exports
 */
function generateIndexFile(components: Array<{ name: string; hasField: boolean }>): string {
  const exports = components
    .map(({ name, hasField }) => {
      let exp = `export { ${name}, type ${name}Props } from './${name}/${name}';`;
      if (hasField) {
        exp += `\nexport { ${name}Field, type ${name}FieldProps } from './${name}/${name}Field';`;
      }
      return exp;
    })
    .join('\n');

  return `/**
 * Generated Components Index
 *
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY
 */

${exports}
`;
}

/**
 * Generate component-level index file
 */
function generateComponentIndex(name: string, hasField: boolean): string {
  let exports = `export { ${name}, type ${name}Props } from './${name}';`;
  if (hasField) {
    exports += `\nexport { ${name}Field, type ${name}FieldProps } from './${name}Field';`;
  }
  return exports + '\n';
}

/**
 * Main generator function
 */
async function main() {
  console.log('🏭 Foundry Component Generator\n');

  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  // Find all schema files
  const schemaFiles = fs
    .readdirSync(SCHEMAS_DIR)
    .filter((f) => f.endsWith('.schema.json') && !f.startsWith('component.'));

  console.log(`📋 Found ${schemaFiles.length} component schemas\n`);

  const generatedComponents: Array<{ name: string; hasField: boolean }> = [];

  for (const schemaFile of schemaFiles) {
    const schemaPath = path.join(SCHEMAS_DIR, schemaFile);
    const schema = loadSchema(schemaPath);

    if (!schema) continue;

    console.log(`⚙️  Generating ${schema.name}...`);

    // Create component directory
    const componentDir = path.join(OUTPUT_DIR, schema.name);
    if (!fs.existsSync(componentDir)) {
      fs.mkdirSync(componentDir, { recursive: true });
    }

    // Generate main component file
    const componentCode = generateComponent(schema);
    const componentPath = path.join(componentDir, `${schema.name}.tsx`);
    fs.writeFileSync(componentPath, componentCode);

    // Generate Field wrapper for input components
    const fieldCode = generateFieldComponent(schema);
    const hasField = fieldCode !== null;

    if (hasField) {
      const fieldPath = path.join(componentDir, `${schema.name}Field.tsx`);
      fs.writeFileSync(fieldPath, fieldCode);
      console.log(`   ✅ ${schema.name} + ${schema.name}Field generated`);
    } else {
      console.log(`   ✅ ${schema.name} generated`);
    }

    // Generate component index file
    const indexCode = generateComponentIndex(schema.name, hasField);
    fs.writeFileSync(path.join(componentDir, 'index.ts'), indexCode);

    generatedComponents.push({ name: schema.name, hasField });
  }

  // Generate main index file
  const indexPath = path.join(OUTPUT_DIR, 'index.ts');
  fs.writeFileSync(indexPath, generateIndexFile(generatedComponents));

  console.log(
    `\n✨ Generated ${generatedComponents.length} components to src/components-generated/`,
  );
  console.log('\nGenerated components:');
  generatedComponents.forEach(({ name, hasField }) => {
    console.log(`  - ${name}${hasField ? ' (+ Field wrapper)' : ''}`);
  });
}

main().catch(console.error);
