#!/usr/bin/env tsx
/**
 * Token Generator
 *
 * Reads token JSON files from foundry/tokens/ and generates:
 * - CSS custom properties
 * - TypeScript token exports
 * - Tailwind preset
 *
 * Usage: pnpm foundry:tokens
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const FOUNDRY_DIR = path.join(__dirname, '..');
const TOKENS_DIR = path.join(FOUNDRY_DIR, 'tokens');
const THEMES_DIR = path.join(TOKENS_DIR, 'themes');
const OUTPUT_DIR = path.join(FOUNDRY_DIR, '..', 'src', 'tokens-generated');

interface TokenFile {
  [key: string]: unknown;
}

function loadTokenFile(filePath: string): TokenFile | null {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    return JSON.parse(content);
  } catch (error) {
    console.error(`Failed to load token file: ${filePath}`, error);
    return null;
  }
}

function resolveTokenReferences(value: string, tokens: Record<string, unknown>): string {
  // Replace {token.path} references with actual values
  return value.replace(/\{([^}]+)\}/g, (_, tokenPath) => {
    const parts = tokenPath.split('.');
    let current: unknown = tokens;

    for (const part of parts) {
      if (current && typeof current === 'object' && part in current) {
        current = (current as Record<string, unknown>)[part];
      } else {
        return `var(--${tokenPath.replace(/\./g, '-')})`;
      }
    }

    return typeof current === 'string' ? current : `var(--${tokenPath.replace(/\./g, '-')})`;
  });
}

function flattenTokens(obj: unknown, prefix = ''): Record<string, string> {
  const result: Record<string, string> = {};

  if (typeof obj !== 'object' || obj === null) {
    return result;
  }

  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith('$')) continue; // Skip meta keys like $schema

    const tokenName = prefix ? `${prefix}-${key}` : key;

    if (typeof value === 'string') {
      result[tokenName] = value;
    } else if (typeof value === 'object' && value !== null) {
      Object.assign(result, flattenTokens(value, tokenName));
    }
  }

  return result;
}

function generateCSSVariables(tokens: Record<string, string>, indent = '  '): string {
  return Object.entries(tokens)
    .map(([name, value]) => `${indent}--${name}: ${value};`)
    .join('\n');
}

function generateCSSFile(allTokens: Record<string, TokenFile>, themes: Record<string, TokenFile>): string {
  // Merge all base tokens
  const baseTokens: Record<string, unknown> = {};
  for (const [, tokens] of Object.entries(allTokens)) {
    Object.assign(baseTokens, tokens);
  }

  const flatBase = flattenTokens(baseTokens);

  // Generate base :root variables
  let css = `/**
 * Design System Tokens
 *
 * @generated This file was generated by foundry/generators/generate-tokens.ts
 * DO NOT EDIT DIRECTLY - modify the token files instead: foundry/tokens/
 */

:root {
${generateCSSVariables(flatBase)}
}
`;

  // Generate theme-specific variables
  for (const [themeName, themeTokens] of Object.entries(themes)) {
    const flatTheme = flattenTokens(themeTokens);

    css += `
/* Theme: ${themeName} */
[data-theme="${themeName}"],
.theme-${themeName} {
${generateCSSVariables(flatTheme)}
}
`;
  }

  // Dark mode media query
  if (themes.dark) {
    const flatDark = flattenTokens(themes.dark);
    css += `
/* System dark mode preference */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
${generateCSSVariables(flatDark, '    ')}
  }
}
`;
  }

  return css;
}

function generateTypeScriptTokens(allTokens: Record<string, TokenFile>): string {
  const tokenExports: string[] = [];

  for (const [fileName, tokens] of Object.entries(allTokens)) {
    const name = fileName.replace('.json', '');
    const flatTokens = flattenTokens(tokens);

    // Generate CSS variable references
    const varRefs = Object.keys(flatTokens)
      .map(key => `  '${key}': 'var(--${key})',`)
      .join('\n');

    tokenExports.push(`
export const ${name}Tokens = {
${varRefs}
} as const;

export type ${name.charAt(0).toUpperCase() + name.slice(1)}Tokens = typeof ${name}Tokens;
`);
  }

  return `/**
 * TypeScript Token Exports
 *
 * @generated This file was generated by foundry/generators/generate-tokens.ts
 * DO NOT EDIT DIRECTLY
 */
${tokenExports.join('\n')}
`;
}

function generateTailwindPreset(allTokens: Record<string, TokenFile>): string {
  const colors: Record<string, string> = {};
  const spacing: Record<string, string> = {};
  const fontSize: Record<string, string> = {};
  const borderRadius: Record<string, string> = {};

  // Extract colors
  if (allTokens.colors) {
    const flatColors = flattenTokens(allTokens.colors);
    for (const [key, value] of Object.entries(flatColors)) {
      if (!key.includes('description')) {
        colors[key.replace(/-/g, '.')] = `var(--${key})`;
      }
    }
  }

  // Extract spacing
  if (allTokens.spacing) {
    const flatSpacing = flattenTokens(allTokens.spacing);
    for (const [key, value] of Object.entries(flatSpacing)) {
      if (key.startsWith('scale-') || key.startsWith('semantic-')) {
        const shortKey = key.replace('scale-', '').replace('semantic-', '');
        spacing[shortKey] = `var(--${key})`;
      }
    }
  }

  return `/**
 * Tailwind CSS Preset
 *
 * @generated This file was generated by foundry/generators/generate-tokens.ts
 * DO NOT EDIT DIRECTLY
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        // Semantic colors
        primary: {
          DEFAULT: 'var(--colors-semantic-primary)',
          foreground: 'var(--colors-surface-background)',
        },
        secondary: {
          DEFAULT: 'var(--colors-semantic-secondary)',
          foreground: 'var(--colors-surface-background)',
        },
        destructive: {
          DEFAULT: 'var(--colors-semantic-destructive)',
          foreground: 'var(--colors-surface-background)',
        },
        success: {
          DEFAULT: 'var(--colors-semantic-success)',
          foreground: 'var(--colors-surface-background)',
        },
        warning: {
          DEFAULT: 'var(--colors-semantic-warning)',
          foreground: 'var(--colors-surface-background)',
        },
        // Surface colors
        background: 'var(--colors-surface-background)',
        foreground: 'var(--colors-surface-foreground)',
        card: {
          DEFAULT: 'var(--colors-surface-card)',
          foreground: 'var(--colors-surface-cardForeground)',
        },
        popover: {
          DEFAULT: 'var(--colors-surface-popover)',
          foreground: 'var(--colors-surface-popoverForeground)',
        },
        muted: {
          DEFAULT: 'var(--colors-surface-muted)',
          foreground: 'var(--colors-surface-mutedForeground)',
        },
        accent: {
          DEFAULT: 'var(--colors-surface-muted)',
          foreground: 'var(--colors-surface-foreground)',
        },
        // Border
        border: 'var(--colors-border-default)',
        input: 'var(--colors-border-input)',
        ring: 'var(--colors-border-ring)',
      },
      borderRadius: {
        sm: 'var(--radius-scale-sm)',
        md: 'var(--radius-scale-md)',
        lg: 'var(--radius-scale-lg)',
        xl: 'var(--radius-scale-xl)',
      },
      fontFamily: {
        sans: 'var(--typography-fontFamily-sans)',
        mono: 'var(--typography-fontFamily-mono)',
      },
    },
  },
  plugins: [],
};
`;
}

async function main() {
  console.log('🎨 Foundry Token Generator\n');

  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  // Load all token files
  const tokenFiles = fs.readdirSync(TOKENS_DIR)
    .filter(f => f.endsWith('.json'));

  const allTokens: Record<string, TokenFile> = {};

  for (const file of tokenFiles) {
    const tokens = loadTokenFile(path.join(TOKENS_DIR, file));
    if (tokens) {
      const name = file.replace('.json', '');
      allTokens[name] = tokens;
      console.log(`📦 Loaded ${file}`);
    }
  }

  // Load theme files
  const themes: Record<string, TokenFile> = {};
  if (fs.existsSync(THEMES_DIR)) {
    const themeFiles = fs.readdirSync(THEMES_DIR)
      .filter(f => f.endsWith('.json'));

    for (const file of themeFiles) {
      const tokens = loadTokenFile(path.join(THEMES_DIR, file));
      if (tokens) {
        const name = file.replace('.json', '');
        themes[name] = tokens;
        console.log(`🎭 Loaded theme: ${name}`);
      }
    }
  }

  // Generate CSS
  console.log('\n⚙️  Generating CSS variables...');
  const css = generateCSSFile(allTokens, themes);
  fs.writeFileSync(path.join(OUTPUT_DIR, 'tokens.css'), css);
  console.log('   ✅ tokens.css');

  // Generate TypeScript
  console.log('⚙️  Generating TypeScript exports...');
  const ts = generateTypeScriptTokens(allTokens);
  fs.writeFileSync(path.join(OUTPUT_DIR, 'tokens.ts'), ts);
  console.log('   ✅ tokens.ts');

  // Generate Tailwind preset
  console.log('⚙️  Generating Tailwind preset...');
  const tailwind = generateTailwindPreset(allTokens);
  fs.writeFileSync(path.join(OUTPUT_DIR, 'tailwind.preset.cjs'), tailwind);
  console.log('   ✅ tailwind.preset.cjs');

  console.log('\n✨ Token generation complete!');
  console.log(`   Output: src/tokens-generated/`);
}

main().catch(console.error);
