/**
 * Tabs
 * Tab navigation container
 *
 * @category navigation
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/tabs.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const tabsVariants = cva(
  'inline-flex h-10 items-center justify-center rounded-md bg-muted p-1 text-muted-foreground',
  {
    variants: {
      size: {
        sm: 'h-8',
        md: 'h-10',
        lg: 'h-12',
      },
    },
    defaultVariants: {
      size: 'md',
    },
  },
);

export type TabsSize = 'sm' | 'md' | 'lg';

export interface TabsProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'ref'>,
    VariantProps<typeof tabsVariants> {
  size?: 'sm' | 'md' | 'lg';
  role?: string;

  className?: string;
  children?: React.ReactNode;
}

export const Tabs = React.forwardRef<HTMLDivElement, TabsProps>(
  ({ size, role, className, children, ...rest }, ref) => {
    return (
      <div
        ref={ref}
        role={role || 'tablist'}
        className={cn(tabsVariants({ size }), className)}
        {...rest}
      >
        {children}
      </div>
    );
  },
);

Tabs.displayName = 'Tabs';

export default Tabs;
