/**
 * Switch
 * Toggle switch for binary options
 *
 * @category input
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/switch.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const switchVariants = cva(
  'w-full rounded-md border border-input bg-background text-foreground transition-colors placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive',
  {
    variants: {
    size: {
      'sm': 'h-8 px-3 text-sm',
      'md': 'h-10 px-4 text-sm',
      'lg': 'h-12 px-5 text-base'
    }
    },
    defaultVariants: {
      size: 'md'
    },
  }
);

export type SwitchSize = 'sm' | 'md' | 'lg';

export interface SwitchProps
  extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'ref'>,
    VariantProps<typeof switchVariants> {
  size?: 'sm' | 'md' | 'lg';
  checked?: boolean;
  onCheckedChange?: (checked: boolean) => void;
  defaultChecked?: boolean;
  thumb?: React.ReactNode;
  className?: string;
  children?: React.ReactNode;
}

export const Switch = React.forwardRef<HTMLButtonElement, SwitchProps>(
  ({ size, checked, onCheckedChange, defaultChecked, thumb, className, children, ...rest }, ref) => {
    return (
      <button
        ref={ref}
        className={cn(switchVariants({ size }), className)}
        {...rest}
      >
        {children}
      </button>
    );
  }
);

Switch.displayName = 'Switch';



export default Switch;