/**
 * Popover
 * A floating panel that appears near a trigger element
 *
 * @category overlay
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/popover.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const popoverVariants = cva(
  'z-50 rounded-md border bg-popover p-4 text-popover-foreground shadow-md outline-none',
  {
    variants: {
      side: {
        top: '',
        right: '',
        bottom: '',
        left: '',
      },
      animation: {
        none: '',
        fade: 'animate-in fade-in-0',
        scale: 'animate-in fade-in-0 zoom-in-95',
        slide: 'animate-in slide-in-from-bottom-2',
      },
    },
    defaultVariants: {
      side: 'bottom',
      animation: 'fade',
    },
  },
);

export interface PopoverProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'ref'>,
    VariantProps<typeof popoverVariants> {
  side?: 'top' | 'right' | 'bottom' | 'left';
  animation?: 'none' | 'fade' | 'scale' | 'slide';

  className?: string;
  children?: React.ReactNode;
}

export const Popover = React.forwardRef<HTMLDivElement, PopoverProps>(
  ({ side, animation, children, className, ...rest }, ref) => {
    return (
      <div ref={ref} className={cn(popoverVariants({ side, animation }), className)} {...rest}>
        {children}
      </div>
    );
  },
);

Popover.displayName = 'Popover';

export default Popover;
