/**
 * Avatar
 * User avatar with image and fallback
 *
 * @category display
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/avatar.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const avatarVariants = cva('relative flex shrink-0 overflow-hidden rounded-full', {
  variants: {
    size: {
      xs: 'h-6 w-6',
      sm: 'h-8 w-8',
      md: 'h-10 w-10',
      lg: 'h-12 w-12',
      xl: 'h-16 w-16',
    },
    shape: {
      circle: 'rounded-full',
      square: 'rounded-md',
    },
  },
  defaultVariants: {
    size: 'md',
    shape: 'circle',
  },
});

export type AvatarSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';

export interface AvatarProps
  extends Omit<React.HTMLAttributes<HTMLSpanElement>, 'ref'>,
    VariantProps<typeof avatarVariants> {
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  shape?: 'circle' | 'square';
  src?: string;
  alt?: string;
  fallback?: React.ReactNode;
  image?: React.ReactNode;
  className?: string;
  children?: React.ReactNode;
}

export const Avatar = React.forwardRef<HTMLSpanElement, AvatarProps>(
  ({ size, shape, src, alt, fallback, image, className, children, ...rest }, ref) => {
    return (
      <span ref={ref} className={cn(avatarVariants({ size, shape }), className)} {...rest}>
        {src ? (
          <img
            src={src}
            alt={alt || ''}
            className="aspect-square h-full w-full object-cover"
            onError={(e) => {
              e.currentTarget.style.display = 'none';
              const fallbackEl = e.currentTarget.nextElementSibling;
              if (fallbackEl) (fallbackEl as HTMLElement).style.display = 'flex';
            }}
          />
        ) : null}
        <span
          className="flex h-full w-full items-center justify-center bg-muted text-muted-foreground font-medium"
          style={{ display: src ? 'none' : 'flex' }}
        >
          {fallback || children}
        </span>
      </span>
    );
  },
);

Avatar.displayName = 'Avatar';

export default Avatar;
