/**
 * Tooltip
 * A small popup that displays information on hover or focus
 *
 * @category overlay
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/tooltip.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const tooltipVariants = cva(
  'z-50 overflow-hidden rounded-md border bg-popover px-3 py-1.5 text-sm text-popover-foreground shadow-md',
  {
    variants: {
      side: {
        top: '',
        right: '',
        bottom: '',
        left: '',
      },
    },
    defaultVariants: {
      side: 'top',
    },
  },
);

export interface TooltipProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'ref' | 'content'>,
    VariantProps<typeof tooltipVariants> {
  side?: 'top' | 'right' | 'bottom' | 'left';
  content?: React.ReactNode;

  className?: string;
  children?: React.ReactNode;
}

export const Tooltip = React.forwardRef<HTMLDivElement, TooltipProps>(
  ({ side, content, children, className, ...rest }, ref) => {
    return (
      <div ref={ref} role="tooltip" className={cn(tooltipVariants({ side }), className)} {...rest}>
        {content || children}
      </div>
    );
  },
);

Tooltip.displayName = 'Tooltip';

export default Tooltip;
