/**
 * Button
 * Interactive button component for actions and navigation
 *
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/button.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const buttonVariants = cva(
  // Base classes
  'inline-flex items-center justify-center gap-2 font-medium rounded-md transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
  {
    variants: {
    intent: {
      'primary': 'bg-primary text-primary-foreground hover:bg-primary/90',
      'secondary': 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
      'ghost': 'hover:bg-accent hover:text-accent-foreground',
      'destructive': 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
      'success': 'bg-success text-success-foreground hover:bg-success/90',
      'outline': 'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
      'link': 'text-primary underline-offset-4 hover:underline',
    },
    size: {
      'sm': 'h-8 px-3 text-sm',
      'md': 'h-10 px-4 text-sm',
      'lg': 'h-12 px-6 text-base',
    }
    },
    defaultVariants: {
      intent: 'primary',
      size: 'md'
    },
  }
);

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'destructive' | 'success' | 'outline' | 'link';
export type ButtonSize = 'sm' | 'md' | 'lg';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  intent?: 'primary' | 'secondary' | 'ghost' | 'destructive' | 'success' | 'outline' | 'link';
  size?: 'sm' | 'md' | 'lg';
  asChild?: boolean;
  isLoading?: boolean;
  loadingText?: string;
  leftIcon?: ReactNode;
  rightIcon?: ReactNode;
  fullWidth?: boolean;
  className?: string;
  children?: React.ReactNode;
}

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ intent, size, asChild, isLoading, loadingText, leftIcon, rightIcon, fullWidth, className, children, ...rest }, ref) => {
    return (
      <button
        ref={ref}
        className={cn(
          buttonVariants({ intent, size }),
          className
        )}
        {...rest}
      >
        {children}
      </button>
    );
  }
);

Button.displayName = 'Button';

export default Button;