/**
 * Skeleton
 * Loading placeholder with pulse animation
 *
 * @category display
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/skeleton.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const skeletonVariants = cva('animate-pulse rounded-md bg-muted', {
  variants: {
    variant: {
      default: 'rounded-md',
      circular: 'rounded-full',
      text: 'h-4 rounded-sm',
    },
  },
  defaultVariants: {
    variant: 'default',
  },
});

export interface SkeletonProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'ref'>,
    VariantProps<typeof skeletonVariants> {
  variant?: 'default' | 'circular' | 'text';

  className?: string;
  children?: React.ReactNode;
}

export const Skeleton = React.forwardRef<HTMLDivElement, SkeletonProps>(
  ({ variant, className, children, ...rest }, ref) => {
    return <div ref={ref} className={cn(skeletonVariants({ variant }), className)} {...rest} />;
  },
);

Skeleton.displayName = 'Skeleton';

export default Skeleton;
