/**
 * Input
 * Text input field for forms
 *
 * @category input
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/input.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const inputVariants = cva(
  'w-full rounded-md border border-input bg-background text-foreground transition-colors placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive',
  {
    variants: {
    size: {
      'sm': 'h-8 px-3 text-sm',
      'md': 'h-10 px-4 text-sm',
      'lg': 'h-12 px-5 text-base'
    }
    },
    defaultVariants: {
      size: 'md'
    },
  }
);

export type InputSize = 'sm' | 'md' | 'lg';

export interface InputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'ref'>,
    VariantProps<typeof inputVariants> {
  size?: 'sm' | 'md' | 'lg';
  type?: string;
  placeholder?: string;
  startIcon?: React.ReactNode;
  endIcon?: React.ReactNode;
  startAdornment?: React.ReactNode;
  endAdornment?: React.ReactNode;
  className?: string;
  children?: React.ReactNode;
}

export const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ size, type, placeholder, startIcon, endIcon, startAdornment, endAdornment, className, children, ...rest }, ref) => {
    return (
      <div className="relative flex items-center">
        {startAdornment && (
          <span className="absolute left-3 flex items-center pointer-events-none text-muted-foreground">
            {startAdornment}
          </span>
        )}
        <input
          ref={ref}
          
          className={cn(
            inputVariants({ size }),
            startAdornment && 'pl-10',
            endAdornment && 'pr-10',
            className
          )}
          {...rest}
        />
        {endAdornment && (
          <span className="absolute right-3 flex items-center pointer-events-none text-muted-foreground">
            {endAdornment}
          </span>
        )}
      </div>
    );
  }
);

Input.displayName = 'Input';



export default Input;