/**
 * Input
 * Text input field for forms
 *
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/input.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const inputVariants = cva(
  // Base classes
  'inline-flex items-center justify-center gap-2 font-medium rounded-md transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
  {
    variants: {
    size: {
      'sm': 'h-8 px-3 text-sm',
      'md': 'h-10 px-4 text-sm',
      'lg': 'h-12 px-6 text-base',
    }
    },
    defaultVariants: {
      size: 'md'
    },
  }
);

export type InputVariant = string;
export type InputSize = 'sm' | 'md' | 'lg';

export interface InputProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  size?: 'sm' | 'md' | 'lg';
  type?: string;
  placeholder?: string;
  startIcon?: React.ReactNode;
  endIcon?: React.ReactNode;
  className?: string;
  children?: React.ReactNode;
}

export const Input = React.forwardRef<HTMLButtonElement, InputProps>(
  ({ size, type, placeholder, startIcon, endIcon, className, children, ...rest }, ref) => {
    return (
      <button
        ref={ref}
        className={cn(
          inputVariants({ size }),
          className
        )}
        {...rest}
      >
        {children}
      </button>
    );
  }
);

Input.displayName = 'Input';

export default Input;