/**
 * Center
 * A layout component that centers its children both horizontally and vertically
 *
 * @category layout
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/center.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const centerVariants = cva('flex items-center justify-center', {
  variants: {},
  defaultVariants: {},
});

export interface CenterProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'ref'>,
    VariantProps<typeof centerVariants> {
  className?: string;
  children?: React.ReactNode;
}

export const Center = React.forwardRef<HTMLDivElement, CenterProps>(
  ({ children, className, ...rest }, ref) => {
    return (
      <div ref={ref} className={cn(centerVariants({}), className)} {...rest}>
        {children}
      </div>
    );
  },
);

Center.displayName = 'Center';

export default Center;
