/**
 * Card
 * Container for grouping related content
 *
 * @generated This file was generated by foundry/generators/generate-components.ts
 * DO NOT EDIT DIRECTLY - modify the schema instead: foundry/schemas/card.schema.json
 */

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const cardVariants = cva(
  // Base classes
  'inline-flex items-center justify-center gap-2 font-medium rounded-md transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
  {
    variants: {
    variant: {
      'elevated': '',
      'outlined': '',
      'filled': '',
      'ghost': '',
    },
    padding: {
      'none': '',
      'sm': '',
      'md': '',
      'lg': '',
    }
    },
    defaultVariants: {
      variant: 'elevated',
      padding: 'md'
    },
  }
);

export type CardVariant = string;
export type CardSize = string;

export interface CardProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'elevated' | 'outlined' | 'filled' | 'ghost';
  padding?: 'none' | 'sm' | 'md' | 'lg';
  isInteractive?: boolean;
  asChild?: boolean;
  className?: string;
  children?: React.ReactNode;
}

export const Card = React.forwardRef<HTMLButtonElement, CardProps>(
  ({ variant, padding, isInteractive, asChild, className, children, ...rest }, ref) => {
    return (
      <button
        ref={ref}
        className={cn(
          cardVariants({ variant, padding }),
          className
        )}
        {...rest}
      >
        {children}
      </button>
    );
  }
);

Card.displayName = 'Card';

export default Card;